### ISSUE TITLE
Can't edit or delete Menu if it's already created

### ISSUE THREAD

**Issue by BenjaDev** [DeligenceTechnologies/PanoplyCMS#2]
Hey there, I'm evaluating a CMS for meteor apps and just found yours. I think it's great, simple and easy to understand. So when I was testing this, I created a menu and a second menu, then i wanted to delete one of them, but nothing happened. I was asked if i'm sure to delete it, I clicked yes and also, nothing happened. Same as I was trying to edit a menu. 
I'm working on a VM with lubuntu, browser is chromium. 
## EDIT: actually i CAN edit a menu, issue came from browser. But deleteing is still not working.

Sorry for this long message, but I'm still playing around with your CMS and found some more bugs. 
I created 2 articles, 2 menues and 2 categories. 
- 2 Categories: Old, New
- 2 Articles: Old-Car, New-Car
- 2 Menues: Old, New.

So i defined some dependencies, when I click on Old-Menue, the Old-Car should show up, nothing more. Same with New-Menue and New-Car. But only the Old-Car shows up, everytime. 

I will try to understand your code and maybe I could fix some bugs, if it works I'll let you know :) 

And maybe you guys have some ideas to help me, i'd really like to use this CMS.

**Comment by prafulc** [comment]
Are you testing master branch or dev2?

**Comment by prafulc** [comment]
Hi BenjaDev, thanks for reporting issue. This issues is resolved now.

**Comment by BenjaDev** [comment]
Thanks for your effort. But I'm still having problems with the menu. 
like before: I create category -> Old, second category -> new, I create Menu -> Old, I create second menu -> new. I only can choose between articles or categories, but nothing more. If I choose category, i should be able to choose old or new, right? But there aren't any options to choose. So i safe the menu like that, then when i edit this menu, i actually can choose between old and new, but after choosing and saving again, the menu is gone -> deleted or lost somewhere :(

**Comment by shakshipandey** [comment]
Hi BenjaDev, thanks for reporting issue. We have taken care of this issue.
